title: This is my life
author: Shannon Jose Gomez
email: shannongomez60@yahoo.in
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  Welcome all to the story of my life.

# social links
twitter_username: generalzodd_ # DO NOT include the @ character, or else the build will fail!
github_username:  generalzoddd # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
